### ISSUE TITLE
Details on data collection and annotation

### ISSUE THREAD

**Issue by ogencoglu** [Saichethan/TRACT#1]
Thanks for the dataset.

For scientific publications using the dataset, what are the details of the procedure to collect data as well as the details of the annotation process?

How many tweets were initially collected? By which method and tools? Timeline? How were they filtered? How many annotators were employed? Which tools used? What are the scientific criteria for annotations?

**Comment by Saichethan** [comment]
Hello, @ogencoglu Thank you for your interest in our dataset. A paper containing all the details about data and detailed analysis will be published soon. feel free to try different approaches on this data.

you can also access this data through [Kaggle](https://www.kaggle.com/saichethanmreddy/tract-corpus)
